name: ❓ Question
description: Ask a question about anything related to Lilypad
labels: [question]

body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: How can we help?
    validations:
      required: true
