name: railway

on:
  release:
    types: [published]
  push:
    branches:
      - hosted-lilypad

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./client/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./client
        run: pnpm install

      - name: Build client
        working-directory: ./client
        run: pnpm run build:local

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.6/install.sh | sh

      - name: Set up Python
        run: uv python install 3.10

      - name: Build Package
        run: uv build

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./client/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./client
        run: pnpm install

      - name: Build client
        working-directory: ./client
        run: pnpm run build:local

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.6/install.sh | sh

      - name: Set up Python
        run: uv python install 3.10

      - name: Build Package
        run: uv build

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service practical-connection
