name: release
run-name: ${{ github.actor }} is uploading a new release to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "./client/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./client
        run: pnpm install

      - name: Build client
        working-directory: ./client
        run: pnpm run build:local

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.6/install.sh | sh

      - name: Set up Python
        run: uv python install 3.10

      - name: Build Package
        run: uv build

      - name: Publish Python Package
        run: uvx twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
